### ISSUE TITLE
Allow to sign-in with existing local sign-ins

### ISSUE THREAD

**Issue by nmehlei** [GSingh01/ad-b2c-react-native#20]
Usually, the user will always be already signed-in on at least some of the social providers (Google, Facebook, Apple, ...) at the time the sign-in page is shown by this plugin, but he still has to enter both mail address as well as password again. I'm assuming this is a technical restriction (probably due to the usage of a web view), but is this something that can be solved in a different way or is this just the way it has to be?

Looking at the user experience, the 1-click login would, of course, be much better than entering (and remembering) a long mail address and password.

**Comment by GSingh01** [comment]
@nmehlei Sorry for replying too late and  yes you are correct, currently unaware of way to handle it.  
But note that after initial login with offline access, library stores the token in secure store so user don't have to login again and again.
 
But i agree it is not seamless across all apps. I also feel it is little secure too(my personal thoughts) since this way you can keep your logins separate for each app but please feel free to suggest or add commit if there is viable solution.

**Comment by GSingh01** [comment]
@nmehlei new version of library is released which uses expo-web-browser and that should handle this flow.
